// Generated by CoffeeScript 1.4.0
var Que;

Que = (function() {

  function Que() {
    var me;
    me = this;
    me.self = this;
    me.fn = Array.prototype.slice.call(arguments, 0);
    me.i = 0;
  }

  Que.prototype.step = function() {
    var next, self;
    self = this.self;
    next = function() {
      return self.step();
    };
    if (this.i < this.fn.length) {
      return this.fn[this.i++](next);
    }
  };

  Que.prototype.run = function() {
    var _results;
    _results = [];
    while (this.i < this.fn.length) {
      _results.push(this.fn[this.i++]());
    }
    return _results;
  };

  Que.prototype.reset = function() {
    if (this.i === this.fn.length) {
      return this.i = 0;
    }
  };

  return Que;

})();
