// Generated by CoffeeScript 1.4.0
var Que;

Que = (function() {

  function Que() {
    var me;
    me = this;
    me.self = this;
    me.fn = Array.prototype.slice.call(arguments, 0);
    me.i = 0;
  }

  Que.prototype.step = function() {
    var next, self;
    self = this.self;
    next = function() {
      return self.run();
    };
    if (this.i < this.fn.length) {
      this.fn[this.i++](next);
    }
    return this.reset();
  };

  Que.prototype.run = function() {
    while (this.i < this.fn.length) {
      this.fn[this.i++]();
    }
    return this.reset();
  };

  Que.prototype.reset = function() {
    if (this.i = this.fn.length) {
      return this.i = 0;
    }
  };

  return Que;

})();
